ja: Fix file path to avoid build error (#2285)
- This PR fixes a wrong filepath (`configure-*` → `configuring-*`) in
the Japanese book.
- I've encountered an error below when I was building the book in
Japanese.

```bash
$ MDBOOK_BOOK__LANGUAGE=ja mdbook build -d book/ja
2024-08-15 21:52:56 [INFO] (mdbook::book): Book building has started
2024-08-15 21:52:57 [INFO] (mdbook::book): Running the exerciser backend
2024-08-15 21:52:57 [INFO] (mdbook::renderer): Invoking the "exerciser" renderer
2024-08-15 21:52:57 [INFO] (mdbook::book): Running the html backend
2024-08-15 21:52:58 [INFO] (mdbook::book): Running the linkcheck backend
2024-08-15 21:52:58 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
error: File not found: ../configure-gnrt-config-toml.md
  ┌─ chromium/adding-third-party-crates/resolving-problems/build-scripts-which-generate-code.md:5:23
  │
5 │ もしファイルが作成されるようになっていたら、[`gnrt_config.toml`](../configure-gnrt-config-toml.md) を変更して、クレートに `build-script-outputs` を追加します。これが推移的依存関係（Chromium コードが直接依存すべきでない依存関係）の場合は、`allow-first-party-usage=false` も追加します。このファイルには、すでにいくつかの例が含まれています。
  │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: ../configure-gnrt-config-toml.md

Error: One or more incorrect links
2024-08-15 21:52:58 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2024-08-15 21:52:58 [ERROR] (mdbook::utils): Error: Rendering failed
2024-08-15 21:52:58 [ERROR] (mdbook::utils):    Caused By: The "linkcheck" renderer failed
```